name: thecatredis
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.1
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  http: ^1.2.2
  appinio_swiper: ^2.1.1
  cached_network_image: ^3.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

#flutter pub run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffbf00"
  image: assets/logo_cat.png
  color_dark: "#121212"
  image_dark: assets/logo_cat_dark.png

#flutter pub run flutter_launcher_icons
flutter_launcher_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/icon_win.png"
    icon_size: 48 # min:48, max:256, default: 48

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

